import asyncio
import typing

def get_loop(self, *args, **kwargs) -> typing.Optional[asyncio.AbstractEventLoop]: ...
def await_if_required(target: typing.Callable) -> typing.Callable[..., typing.Any]: ...
